# Generated by Django 5.1.3 on 2024-11-23 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Text'), (2, 'Markdown'), (3, 'HTML')], default=1),
        ),
    ]
