# Generated by Django 5.1.3 on 2024-11-23 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_content_alter_post_group_alter_post_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postchangelog',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
