# Generated by Django 5.1.3 on 2024-11-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postchangelog_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postchangelog',
            name='description',
        ),
    ]
